<%@ Page Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="InstructionMaster.aspx.cs" Inherits="InstructionMaster" Title="Untitled Page" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    &nbsp;<asp:ScriptManager id="ScriptManager1" runat="server"></asp:ScriptManager>
    <asp:UpdatePanel id="UpdatePanel1" runat="server">
        <contenttemplate>
<TABLE style="WIDTH: 495px; HEIGHT: 266px"><TBODY><TR><TD style="WIDTH: 100px; HEIGHT: 274px"><asp:Panel id="pnlInstructions" runat="server" Width="100%" Height="100%" GroupingText="Instructions"><TABLE style="WIDTH: 204px; HEIGHT: 115px"><TBODY><TR><TD style="TEXT-ALIGN: center" colSpan=2><asp:Label id="Label6ere" runat="server" Text="Instruction Master" Font-Bold="True" Font-Size="Medium" __designer:wfdid="w8"></asp:Label></TD><TD style="WIDTH: 100px"></TD></TR><TR><TD style="WIDTH: 100px"><asp:Label id="Label1" runat="server" Width="96px" Text="Instruction Id"></asp:Label></TD><TD style="WIDTH: 206px"><asp:TextBox id="txtInstructionId" runat="server" OnTextChanged="txtInstructionId_TextChanged" AutoPostBack="True"></asp:TextBox></TD><TD style="WIDTH: 100px"></TD></TR><TR><TD style="WIDTH: 100px"><asp:Label id="Label2" runat="server" Text="Instruction Type"></asp:Label></TD><TD style="WIDTH: 206px"><asp:DropDownList id="cmbInsType" runat="server"><asp:ListItem>select</asp:ListItem>
<asp:ListItem Value="0">Donor</asp:ListItem>
<asp:ListItem Value="0">Inmates</asp:ListItem>
</asp:DropDownList></TD><TD style="WIDTH: 100px"></TD></TR><TR><TD style="WIDTH: 100px"><asp:Label id="Label3" runat="server" Text="Instruction Head"></asp:Label></TD><TD style="WIDTH: 206px"><asp:TextBox id="txtInsHead" runat="server"></asp:TextBox></TD><TD style="WIDTH: 100px"></TD></TR><TR><TD style="WIDTH: 100px; HEIGHT: 109px"><asp:Label id="Label4" runat="server" Width="119px" Text="Instruction Details"></asp:Label></TD><TD style="WIDTH: 206px; HEIGHT: 109px"><asp:TextBox id="txtDetails" runat="server" Width="390px" Height="99px" TextMode="MultiLine"></asp:TextBox></TD><TD style="WIDTH: 100px; HEIGHT: 109px"></TD></TR><TR><TD style="TEXT-ALIGN: center" colSpan=2><asp:Button id="btnSave" onclick="btnSave_Click" runat="server" Text="Save" CssClass="btnStyle_small" __designer:wfdid="w5"></asp:Button> <asp:Button id="btnDelete" onclick="btnDelete_Click" runat="server" Text="Delete" CssClass="btnStyle_small" __designer:wfdid="w6"></asp:Button> <asp:Button id="btnClear" onclick="btnClear_Click" runat="server" Text="Clear" CssClass="btnStyle_small" __designer:wfdid="w7"></asp:Button> <asp:Button id="btnPublicDisplay" runat="server" Text="Public Display" Font-Bold="True" BackColor="#C0C0FF" CssClass="btnStyle_large" __designer:wfdid="w9" OnClick="btnPublicDisplay_Click"></asp:Button></TD><TD style="WIDTH: 100px"></TD></TR></TBODY></TABLE></asp:Panel></TD><TD style="WIDTH: 100px; HEIGHT: 274px"></TD><TD style="WIDTH: 100px; HEIGHT: 274px"></TD></TR><TR><TD style="WIDTH: 100px"><asp:Panel id="pnlGrid" runat="server" Width="125px" Height="50px" GroupingText="Instruction"><asp:GridView id="dtgInstructions" runat="server" Width="700px" ForeColor="#333333" OnPageIndexChanging="dtgInstructions_PageIndexChanging" AllowPaging="True" OnSelectedIndexChanged="dtgInstructions_SelectedIndexChanged" OnRowCreated="dtgInstructions_RowCreated" CellPadding="4" GridLines="None" PageSize="5">
<FooterStyle BackColor="#507CD1" ForeColor="White" Font-Bold="True"></FooterStyle>
<Columns>
<asp:CommandField SelectText="" ShowSelectButton="True"></asp:CommandField>
</Columns>

<RowStyle BackColor="#EFF3FB"></RowStyle>

<EditRowStyle BackColor="#2461BF"></EditRowStyle>

<SelectedRowStyle BackColor="#D1DDF1" ForeColor="#333333" Font-Bold="True"></SelectedRowStyle>

<PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center"></PagerStyle>

<HeaderStyle BackColor="#507CD1" ForeColor="White" Font-Bold="True"></HeaderStyle>

<AlternatingRowStyle BackColor="White"></AlternatingRowStyle>
</asp:GridView></asp:Panel></TD><TD style="WIDTH: 100px"></TD><TD style="WIDTH: 100px"></TD></TR><TR><TD style="WIDTH: 100px"><asp:Panel id="pnlMessage" runat="server" CssClass="ModalWindow" _designer:dtid="562958543355909" _=""><asp:Panel id="Panel4" runat="server" BackColor="LightSteelBlue" BorderStyle="Outset"><asp:Label id="lblHead" runat="server" ForeColor="MediumBlue" Font-Bold="True" Text="Tsunami ARMS - "></asp:Label></asp:Panel> <ajaxToolkit:ModalPopupExtender id="ModalPopupExtender1" runat="server" TargetControlID="btnHidden" RepositionMode="RepositionOnWindowResize" PopupControlID="pnlMessage">
                </ajaxToolkit:ModalPopupExtender> <asp:Button style="DISPLAY: none" id="btnHidden" onclick="btnHidden_Click" runat="server" Text="Hidden"></asp:Button> <asp:TextBox id="TextBox2" runat="server" AutoPostBack="True" OnTextChanged="TextBox1_TextChanged" Visible="False"></asp:TextBox> <asp:Label id="Label5" runat="server" Text="Label" Visible="False"></asp:Label> <BR /><asp:Panel id="pnlYesNo" runat="server" Width="237px" Height="142px" HorizontalAlign="Center"><TABLE><TBODY><TR><TD vAlign=middle align=center colSpan=1></TD><TD style="WIDTH: 200px" vAlign=middle align=center colSpan=3><asp:Label id="lblMsg" runat="server" ForeColor="Black" Text="Do you want to save?" Font-Size="Small"></asp:Label></TD></TR><TR><TD style="WIDTH: 21px" vAlign=middle align=center></TD><TD vAlign=middle align=center></TD><TD vAlign=middle align=center></TD></TR><TR><TD style="WIDTH: 21px" vAlign=middle align=center></TD><TD vAlign=middle align=center>&nbsp;&nbsp;<asp:Button id="btnYes" onclick="btnYes_Click" runat="server" Width="50px" CausesValidation="False" Text="Yes" CssClass="btnStyle"></asp:Button> <asp:Button id="btnNo" onclick="btnNo_Click" runat="server" Width="50px" CausesValidation="False" Text="No" CssClass="btnStyle"></asp:Button>&nbsp;</TD><TD vAlign=middle align=center>&nbsp;</TD></TR><TR><TD vAlign=middle align=center></TD><TD vAlign=middle align=center></TD><TD vAlign=middle align=center></TD></TR></TBODY></TABLE></asp:Panel> <asp:Panel id="pnlOk" runat="server" Width="195%" Height="113%" HorizontalAlign="Center"><TABLE><TBODY><TR><TD align=center colSpan=1></TD><TD style="WIDTH: 182px" align=center colSpan=3><asp:Label id="lblOk" runat="server" ForeColor="Black" Text="Do you want to ?" Font-Size="Small"></asp:Label></TD></TR><TR><TD></TD><TD style="WIDTH: 136px"></TD><TD style="WIDTH: 19px"></TD></TR><TR><TD></TD><TD style="WIDTH: 136px" align=center>&nbsp;&nbsp;&nbsp;&nbsp; <asp:Button id="btnOk" onclick="btnOk_Click" runat="server" Width="50px" CausesValidation="False" Text="OK" CssClass="btnStyle"></asp:Button> &nbsp; </TD><TD style="WIDTH: 19px" align=center>&nbsp;</TD></TR><TR><TD></TD><TD style="WIDTH: 136px" align=center></TD><TD style="WIDTH: 19px" align=center></TD></TR></TBODY></TABLE></asp:Panel> </asp:Panel></TD><TD style="WIDTH: 100px"></TD><TD style="WIDTH: 100px"></TD></TR></TBODY></TABLE>
</contenttemplate>
    </asp:UpdatePanel>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder3" Runat="Server">
</asp:Content>

